export namespace Flag {
export const CODEWIZARD_AUTO_SHARE = truthy("CODEWIZARD_AUTO_SHARE")
export const CODEWIZARD_CONFIG = process.env["CODEWIZARD_CONFIG"]
export const CODEWIZARD_CONFIG_DIR = process.env["CODEWIZARD_CONFIG_DIR"]
export const CODEWIZARD_CONFIG_CONTENT = process.env["CODEWIZARD_CONFIG_CONTENT"]
export const CODEWIZARD_DISABLE_AUTOUPDATE = truthy("CODEWIZARD_DISABLE_AUTOUPDATE")
export const CODEWIZARD_DISABLE_PRUNE = truthy("CODEWIZARD_DISABLE_PRUNE")
export const CODEWIZARD_PERMISSION = process.env["CODEWIZARD_PERMISSION"]
export const CODEWIZARD_DISABLE_DEFAULT_PLUGINS = truthy("CODEWIZARD_DISABLE_DEFAULT_PLUGINS")
export const CODEWIZARD_DISABLE_LSP_DOWNLOAD = truthy("CODEWIZARD_DISABLE_LSP_DOWNLOAD")
export const CODEWIZARD_ENABLE_EXPERIMENTAL_MODELS = truthy("CODEWIZARD_ENABLE_EXPERIMENTAL_MODELS")
export const CODEWIZARD_DISABLE_AUTOCOMPACT = truthy("CODEWIZARD_DISABLE_AUTOCOMPACT")
export const CODEWIZARD_FAKE_VCS = process.env["CODEWIZARD_FAKE_VCS"]
// Feature Flags
export const CODEWIZARD_EXPERIMENTAL = truthy("CODEWIZARD_EXPERIMENTAL")
export const CODEWIZARD_EXPERIMENTAL_ICON_DISCOVERY =
  CODEWIZARD_EXPERIMENTAL || truthy("CODEWIZARD_EXPERIMENTAL_ICON_DISCOVERY")
export const CODEWIZARD_EXPERIMENTAL_WATCHER = CODEWIZARD_EXPERIMENTAL || truthy("CODEWIZARD_EXPERIMENTAL_WATCHER")
export const CODEWIZARD_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = truthy("CODEWIZARD_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
export const CODEWIZARD_ENABLE_EXA =
  truthy("CODEWIZARD_ENABLE_EXA") || CODEWIZARD_EXPERIMENTAL || truthy("CODEWIZARD_EXPERIMENTAL_EXA")
export const CODEWIZARD_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("CODEWIZARD_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
export const CODEWIZARD_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("CODEWIZARD_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")

  function truthy(key: string) {
    const value = process.env[key]?.toLowerCase()
    return value === "true" || value === "1"
  }

  function number(key: string) {
    const value = process.env[key]
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}
